Fitness/Controllers/InfofitnessesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fitness.Models;
using Microsoft.AspNetCore.Hosting;


namespace Fitness.Controllers
{
    public class InfofitnessesController : Controller
    {
        private readonly ModelContext _context;
      
        private readonly IWebHostEnvironment _webHostEnvironment;

        public InfofitnessesController(ModelContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Infofitnesses
        public async Task<IActionResult> Index()
        {
            var modelContext = _context.Infofitnesses.Include(i => i.Inprofile);
            return View(await modelContext.ToListAsync());
        }

        // GET: Infofitnesses/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.Infofitnesses == null)
            {
                return NotFound();
            }

            var infofitness = await _context.Infofitnesses
                .Include(i => i.Inprofile)
                .FirstOrDefaultAsync(m => m.Idif == id);
            if (infofitness == null)
            {
                return NotFound();
            }

            return View(infofitness);
        }

        // GET: Infofitnesses/Create
        public IActionResult Create()
        {
            ViewData["Inprofileid"] = new SelectList(_context.Profiles, "Profileid", "Profileid");
            return View();
        }

        // POST: Infofitnesses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idif,Email,Phone,Location,Aboutus,Facebook,Linkedin,ImageFileaboutus,Inprofileid")] Infofitness infofitness)
        {
            if (ModelState.IsValid)
            {
                String wwwRootPath = _webHostEnvironment.WebRootPath;
                String filename = Guid.NewGuid().ToString() + "_" + infofitness.ImageFileaboutus.FileName;
                String path = Path.Combine(wwwRootPath + "/images/" + filename);

                using (var filestrem = new FileStream(path, FileMode.Create))
                {
                    await infofitness.ImageFileaboutus.CopyToAsync(filestrem);
                }
                infofitness.Photoaboutus = filename;
                _context.Add(infofitness);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Inprofileid"] = new SelectList(_context.Profiles, "Profileid", "Profileid", infofitness.Inprofileid);
            return View(infofitness);
        }








        // GET: Infofitnesses/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null || _context.Infofitnesses == null)
            {
                return NotFound();
            }

            var infofitness = await _context.Infofitnesses.FindAsync(id);
            if (infofitness == null)
            {
                return NotFound();
            }

           
            return View(infofitness);
        }

        // POST: Infofitnesses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Idif,Email,Phone,Location,Aboutus,Facebook,Linkedin,ImageFileaboutus,Inprofileid")] Infofitness infofitness)
        {
            if (id != infofitness.Idif)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                 
                    if (infofitness.ImageFileaboutus != null)
                    {
                        string wwwRootPath = _webHostEnvironment.WebRootPath;
                        string filename = Guid.NewGuid().ToString() + "_" + infofitness.ImageFileaboutus.FileName;
                        string path = Path.Combine(wwwRootPath + "/images/" + filename);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await infofitness.ImageFileaboutus.CopyToAsync(fileStream);
                        }

                      
                        infofitness.Photoaboutus = filename;
                    }

              
                    _context.Update(infofitness);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    
                }
                return RedirectToAction(nameof(Index));
            }

            
            ViewData["Inprofileid"] = new SelectList(_context.Profiles, "Profileid", "Profileid", infofitness.Inprofileid);
            return View(infofitness);
        }

        


        // GET: Infofitnesses/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null || _context.Infofitnesses == null)
            {
                return NotFound();
            }

            var infofitness = await _context.Infofitnesses
                .Include(i => i.Inprofile)
                .FirstOrDefaultAsync(m => m.Idif == id);
            if (infofitness == null)
            {
                return NotFound();
            }

            return View(infofitness);
        }

        // POST: Infofitnesses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            if (_context.Infofitnesses == null)
            {
                return Problem("Entity set 'ModelContext.Infofitnesses'  is null.");
            }
            var infofitness = await _context.Infofitnesses.FindAsync(id);
            if (infofitness != null)
            {
                _context.Infofitnesses.Remove(infofitness);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InfofitnessExists(decimal id)
        {
            return _context.Infofitnesses.Any(e => e.Idif == id);
        }
    }
}

Fitness/Views/Infofitnesses/Create.cshtml
@model Fitness.Models.Infofitness

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Infofitness</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Aboutus" class="control-label"></label>
                <input asp-for="Aboutus" class="form-control" />
                <span asp-validation-for="Aboutus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Facebook" class="control-label"></label>
                <input asp-for="Facebook" class="form-control" />
                <span asp-validation-for="Facebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Linkedin" class="control-label"></label>
                <input asp-for="Linkedin" class="form-control" />
                <span asp-validation-for="Linkedin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photoaboutus" class="control-label"></label>
                <input asp-for="Photoaboutus" class="form-control" />
                <span asp-validation-for="Photoaboutus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inprofileid" class="control-label"></label>
                <select asp-for="Inprofileid" class ="form-control" asp-items="ViewBag.Inprofileid"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fitness/Views/Infofitnesses/Delete.cshtml
@model Fitness.Models.Infofitness

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Infofitness</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aboutus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aboutus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Facebook)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Facebook)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Linkedin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Linkedin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photoaboutus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photoaboutus)
            @Url.Content("~/images/" + Model.Photoaboutus)"
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inprofile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inprofile.Profileid)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Idif" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Fitness/Views/Infofitnesses/Details.cshtml
@model Fitness.Models.Infofitness

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Infofitness</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aboutus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aboutus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Facebook)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Facebook)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Linkedin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Linkedin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photoaboutus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photoaboutus)
            @Url.Content("~/images/" + Model.Photoaboutus)"
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inprofile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inprofile.Profileid)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Idif">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Fitness/Views/Infofitnesses/Edit.cshtml
@model Fitness.Models.Infofitness

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Corona Admin</title>
<!-- plugins:css -->
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/mdi/css/materialdesignicons.min.css">
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/css/vendor.bundle.base.css">
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/jvectormap/jquery-jvectormap.css">
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/flag-icon-css/css/flag-icon.min.css">
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/owl-carousel-2/owl.carousel.min.css">
<link rel="stylesheet" href="~/DesignAdman/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
<link rel="stylesheet" href="~/DesignAdman/assets/css/style.css">
<link rel="shortcut icon" href="~/DesignAdman/assets/images/favicon.png" />


<link rel="stylesheet" href="~/css/ManageStaticPagesEdit.css" />


<div class="content-wrapper bg-dark text-light">
    <div class="main-panel">
        <div class="col-12 grid-margin">
            <div class="card bg-secondary text-light">
                <div class="card-body">
                    <h1 class="card-title text-center">Edit Infofitness</h1>
                    <hr class="border-secondary">
                    <div class="row">
                        <div class="col-md-12">
                            @using (Html.BeginForm("Edit", "Infofitnesses", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                                <input type="hidden" asp-for="Idif" />

                                <!-- Email Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Email" class="control-label text-light">Email</label>
                                    <input asp-for="Email" class="form-control custom-field" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>

                                <!-- Phone Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Phone" class="control-label text-light">Phone</label>
                                    <input asp-for="Phone" class="form-control custom-field" />
                                    <span asp-validation-for="Phone" class="text-danger"></span>
                                </div>

                                <!-- Location Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Location" class="control-label text-light">Location</label>
                                    <input asp-for="Location" class="form-control custom-field" />
                                    <span asp-validation-for="Location" class="text-danger"></span>
                                </div>

                                <!-- About Us Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Aboutus" class="control-label text-light">About Us</label>
                                    <textarea asp-for="Aboutus" class="form-control custom-field" rows="4"></textarea>
                                    <span asp-validation-for="Aboutus" class="text-danger"></span>
                                </div>

                                <!-- Facebook Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Facebook" class="control-label text-light">Facebook</label>
                                    <input asp-for="Facebook" class="form-control custom-field" />
                                    <span asp-validation-for="Facebook" class="text-danger"></span>
                                </div>

                                <!-- LinkedIn Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Linkedin" class="control-label text-light">LinkedIn</label>
                                    <input asp-for="Linkedin" class="form-control custom-field" />
                                    <span asp-validation-for="Linkedin" class="text-danger"></span>
                                </div>

                                <!-- Image Upload Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="ImageFileaboutus" class="control-label text-light">Upload Image</label>
                                    <input asp-for="ImageFileaboutus" type="file" class="form-control custom-field" />
                                    <span asp-validation-for="ImageFileaboutus" class="text-danger"></span>
                                </div>

                                <!-- Profile Select Field -->
                                <div class="form-group mb-4">
                                    <label asp-for="Inprofileid" class="control-label text-light">Profile</label>
                                    <select asp-for="Inprofileid" class="form-control custom-field" asp-items="ViewBag.Inprofileid"></select>
                                    <span asp-validation-for="Inprofileid" class="text-danger"></span>
                                </div>

                                <!-- Buttons -->
                                <div class="form-group text-center">
                                    <input type="submit" value="Save" class="btn btn-primary btn-lg" />
                                    <a href="@Url.Action("Index", "Infofitnesses")" class="btn btn-secondary btn-lg">Back to List</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="~/DesignAdman/assets/vendors/js/vendor.bundle.base.js"></script>
<script src="~/DesignAdman/assets/vendors/chart.js/Chart.min.js"></script>
<script src="~/DesignAdman/assets/vendors/progressbar.js/progressbar.min.js"></script>
<script src="~/DesignAdman/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
<script src="~/DesignAdman/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="~/DesignAdman/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
<script src="~/DesignAdman/assets/js/off-canvas.js"></script>
<script src="~/DesignAdman/assets/js/hoverable-collapse.js"></script>
<script src="~/DesignAdman/assets/js/misc.js"></script>
<script src="~/DesignAdman/assets/js/settings.js"></script>
<script src="~/DesignAdman/assets/js/todolist.js"></script>
<script src="~/DesignAdman/assets/js/dashboard.js"></script>
      