Fitness/Controllers/ProfileUserController.cs
using Fitness.Models;
using iText.Kernel.Pdf;
using iText.Layout.Element;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using iText.Layout;
using System.Net.Mail;
using System.Net;
using iText.Layout.Properties;


namespace Fitness.Controllers

{
	public class ProfileUserController : Controller
	{
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;   
        
		public ProfileUserController(ModelContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
            _webHostEnvironment = webHostEnvironment;
		}



        public IActionResult SendPdf()
        {
            var UserID = Convert.ToDecimal(HttpContext.Session.GetInt32("UserID") ?? 3);
            var User = _context.Profiles.Where(x => x.Profileid == UserID).FirstOrDefault();
            var TypePersone = _context.Typepeople.Where(x => x.Tprofileid == UserID).FirstOrDefault();
            var IDSubscr = _context.Subscriptions.Include(s => s.SidwopNavigation).FirstOrDefault(x => x.Subscrid == TypePersone.Tsubscrid);
            var Idplan = _context.Subscriptions.Include(x => x.Sidwop == IDSubscr.Sidwop);

            byte[] pdfBytes;
            using (MemoryStream ms = new MemoryStream())
            {
                PdfWriter writer = new PdfWriter(ms);
                PdfDocument pdf = new PdfDocument(writer);
                Document document = new Document(pdf);
                
               
                document.Add(new Paragraph("Invoice")
                    .SetTextAlignment(TextAlignment.CENTER)
                    .SetFontSize(18));

                document.Add(new Paragraph($"We appreciate your business with Finess Gym. Below are the details of your recent purchase.")
                 .SetFontSize(14));
                document.Add(new Paragraph($"----------------Your subscription details-------------------")
                   .SetFontSize(14));
               
               
                Table table = new Table(2, true);
                table.AddHeaderCell("information");
                table.AddHeaderCell("Custmer");


                table.AddCell("Name");
                table.AddCell($"{User.Name}{User.Lname}");
               

                table.AddCell("Name Plan");
                table.AddCell($"{IDSubscr.Nameplan}");

                table.AddCell("Start Date");
                table.AddCell($"{TypePersone.Startdate}");

                table.AddCell("End Date");
                table.AddCell($"{TypePersone.Enddate}");

                table.AddCell("Status");
                table.AddCell($"{TypePersone.Status}");

                table.AddCell("Price");
                table.AddCell($"${IDSubscr.Price}");
               
               
                document.Add(table);
                document.Add(new Paragraph("Hello, this is Email by Fitness Gyms "  ));
                document.Close();
             
                pdfBytes = ms.ToArray();
            }

           
            string fromEmail = "bader.sleman2000@gmail.com";
            string toEmail = $"{User.Email}";
            string subject = "Your PDF File";
            string body = "Please find the attached PDF file.";

            using (MailMessage mail = new MailMessage(fromEmail, toEmail))
            {
                mail.Subject = subject;
                mail.Body = body;
                mail.IsBodyHtml = false;

               
                mail.Attachments.Add(new Attachment(new MemoryStream(pdfBytes), "Sample.pdf"));

              
                using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587)) 
                {
                 
                    smtp.Credentials = new NetworkCredential("bader.sleman2000@gmail.com", "bnot ucvx aahn klgr"); 
                    smtp.EnableSsl = true;  

                    try
                    {
                       
                        smtp.Send(mail);
                    }
                    catch (SmtpException ex)
                    { 
                        return Content($"Error sending email: {ex.Message}");
                    }
                }
            }

            TempData["SuccessMessage"] = "Success Send You Email!";
            return RedirectToAction("MyVisaCard");
        }


        public IActionResult Index()
        {
            var profiles = _context.Profiles.Include(p => p.Role).ToList();
            return View(profiles);
        }

        public async Task<IActionResult> Details(decimal? id = 1)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .Include(p => p.Role)
                .FirstOrDefaultAsync(m => m.Profileid == id);

            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

   
        public async Task<IActionResult> Edit(decimal? id = 1)
        {
            if (id == null || _context.Profiles == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.FindAsync(id);

            if (profile == null)
            {
                return NotFound();
            }

            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Rname", profile.Roleid);
            return View(profile);
        }

        // GET: Subscriptions/Details/5
        public async Task<IActionResult> MySubscription(decimal? id = 3)
        {
            if (id == null || _context.Subscriptions == null)
            {
                
                return View(); 
            }

            var typePerson = await _context.Typepeople
                .Include(tp => tp.Tprofile)
                .FirstOrDefaultAsync(tp => tp.Tprofile != null && tp.Tprofile.Profileid == id.Value);

            if (typePerson != null)
            {
                ViewBag.MoreDetils = typePerson;

                var subscription = await _context.Subscriptions
                    .Include(s => s.SidwopNavigation)
                    .FirstOrDefaultAsync(s => s.Subscrid == typePerson.Tsubscrid);

                if (subscription != null)
                {
                    var plan = await _context.Workoutplans
                        .FirstOrDefaultAsync(wp => wp.Idwop == subscription.Sidwop);

                    if (plan != null)
                    {
                        ViewBag.Plan = plan;
                        return View(subscription); 
                    }
                }
            }

           
            return View();
        }


        public async Task<IActionResult> MyVisaCard(decimal? id = 3)
        {
            if (id == null || _context.Payments == null)
            {
                return View();
            }

            var payment = _context.Payments.Where(p => p.Profileid == Convert.ToDecimal(id)).FirstOrDefault();
            if (payment == null)
            {
                return View();
            }

            return View(payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Profileid,Name,Username,Userpassword,ImageFile,DateOfBirth,Email,Lname,Roleid")] Profile profile)
        {
            if (id != profile.Profileid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (profile.ImageFile != null)
                    {
                        string wwwRootPath = _webHostEnvironment.WebRootPath;
                        string filename = Guid.NewGuid().ToString() + "_" + profile.ImageFile.FileName;
                        string path = Path.Combine(wwwRootPath + "/images/" + filename);

                        using (var filestrem = new FileStream(path, FileMode.Create))
                        {
                            await profile.ImageFile.CopyToAsync(filestrem);
                        }
                        profile.Photo = filename;
                    }

                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.Profileid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = profile.Profileid });
            }

         
            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Rname", profile.Roleid);
            return View(profile);
        }

        private bool ProfileExists(decimal id)
        {
            return (_context.Profiles?.Any(e => e.Profileid == id)).GetValueOrDefault();
        }
    }
}

Fitness/Views/profileuser/Details.cshtml
@model Fitness.Models.Profile

@{

    ViewData["Title"] = "Details";
    var UserRoleID = Context.Session.GetInt32("UserRoleID"); 

    if (UserRoleID.HasValue && (UserRoleID == 1))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (UserRoleID.HasValue && (UserRoleID == 2))
    {
        Layout = "~/Views/Shared/_LayoutTrainer.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutProfilePage.cshtml";
    }
   

   
}
<link href="~/DesignProfileUser/style.css" rel="stylesheet" id="bootstrap-css">


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">


<link rel="stylesheet" href="~/DesignProfileUser/ditelsProfile.css" />

<div class="profile-container">
    <div class="profile-header">
        <img src="@Url.Content("~/images/" + Model?.Photo)" alt="User Photo" />
        <h1>@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Lname)</h1>
        <h2>@Html.DisplayFor(model => model.Username)</h2>
    </div>
    <div class="profile-details">
        <div class="detail-item">
            <label>First Name</label>
            <p>@Html.DisplayFor(model => model.Name)</p>
        </div>
        <div class="detail-item">
            <label>Family Name</label>
            <p>@Html.DisplayFor(model => model.Lname)</p>
        </div>
        <div class="detail-item">
            <label>Email</label>
            <p>@Html.DisplayFor(model => model.Email)</p>
        </div>
        <div class="detail-item">
            <label>User Name</label>
            <p>@Html.DisplayFor(model => model.Username)</p>
        </div>
        <div class="detail-item">
            <label>User Password</label>
            <p>@Html.DisplayFor(model => model.Userpassword)</p>
        </div>
        <div class="detail-item">
            <label>Date Of Birth</label>
            <p>@Html.DisplayFor(model => model.DateOfBirth)</p>
        </div>
    </div>
    <a class="edit-button" asp-controller="ProfileUser" asp-action="Edit" asp-route-id="@Model?.Profileid">Edit Your Profile</a>
</div>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

Fitness/Views/profileuser/Edit.cshtml
@model Fitness.Models.Profile

@{
    ViewData["Title"] = "EditProfileUser";
    var UserRoleID = Context.Session.GetInt32("UserRoleID"); 
    if (UserRoleID.HasValue && (UserRoleID == 1 ))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (UserRoleID.HasValue && (UserRoleID == 2))
    {
        Layout = "~/Views/Shared/_LayoutTrainer.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutProfilePage.cshtml";
    }
}

  <link rel="stylesheet" href="~/DesignProfileUser/editProfile.css" /> 


<link href="~/DesignProfileUser/style.css" rel="stylesheet" id="bootstrap-css">

<div class="content-wrapper" style="margin-top: 50px;">
    <div class="container emp-profile">
        
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="profile-img">
                    <img src="@Url.Content("~/images/" + Model?.Photo)" class="img-fluid rounded-circle" width="150" height="150" alt="User Photo" />
                </div>
            </div>
            <div class="col-md-8">
                <div class="profile-head">
                    <h5>
                        @Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Lname)
                    </h5>
                    <h6>
                        @Html.DisplayFor(model => model.Username)
                    </h6>
                   
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-12">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Profileid" />

               
                    <div class="form-row">
                        <div class="form-group">
                            <label asp-for="Name" class="control-label">First Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Lname" class="control-label">Last Name</label>
                            <input asp-for="Lname" class="form-control" />
                            <span asp-validation-for="Lname" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Username" class="control-label">Username</label>
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label asp-for="Userpassword" class="control-label">Password</label>
                            <input asp-for="Userpassword" type="password" class="form-control" />
                            <span asp-validation-for="Userpassword" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="ImageFile" class="control-label">Profile Picture</label>
                            <input asp-for="ImageFile" type="file" class="form-control-file" />
                            <span asp-validation-for="ImageFile" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label asp-for="DateOfBirth" class="control-label">Date of Birth</label>
                            <input asp-for="DateOfBirth" type="date" class="form-control" />
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group text-center">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <a asp-controller="ProfileUser" asp-action="Details" asp-route-id="@Model?.Profileid" class="btn btn-secondary ml-2">Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Fitness/Views/profileuser/MySubscription.cshtml
@model Fitness.Models.Subscription

@{

    ViewData["Title"] = "Details";
    var UserRoleID = Context.Session.GetInt32("UserRoleID"); 

    if (UserRoleID.HasValue && (UserRoleID == 1))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (UserRoleID.HasValue && (UserRoleID == 2))
    {
        Layout = "~/Views/Shared/_LayoutTrainer.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutProfilePage.cshtml";
    }
    var ListMore = ViewBag.MoreDetils;
    var plan = ViewBag.plan;

   
}

<link rel="stylesheet" href="~/css/UserSubscritopnPage.css" />


<link rel="stylesheet" href="~/DesignProfileUser/ditelsProfile.css" />
<div class="container mt-5">
    @if (Model != null && Model.Countweeks != null && Model.Nameplan != null && Model.Price != null && ListMore != null)
    {
        <!-- First Card: Membership Information -->
        <div class="card profile-container shadow-lg rounded-lg mb-4">
            <div class="card-header text-center bg-primary text-white">
                <h1>Your Membership</h1>
            </div>
            <div class="card-body">
                <hr />
                <div class="row">
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>@Html.DisplayNameFor(model => model.Countweeks):</strong>
                            <p>@Html.DisplayFor(model => model.Countweeks) weeks</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>@Html.DisplayNameFor(model => model.Nameplan):</strong>
                            <p>@Html.DisplayFor(model => model.Nameplan)</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>@Html.DisplayNameFor(model => model.Price):</strong>
                            <p>@Html.DisplayFor(model => model.Price) USD</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Start Date:</strong>
                            <p>@ListMore.Startdate?.ToString("yyyy-MM-dd")</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>End Date:</strong>
                            <p>@ListMore.Enddate?.ToString("yyyy-MM-dd")</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Status:</strong>
                            <p>@ListMore.Status</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Second Card: Plan Information -->
        <div class="card profile-container shadow-lg rounded-lg">
            <div class="card-header text-center bg-success text-white">
                <h1>Plan Information</h1>
            </div>
            <div class="card-body">
                <hr />
                <div class="row">
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Count Week:</strong>
                            <p>@plan.Numberofweek</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Goals:</strong>
                            <p>@plan.Goals</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 1:</strong>
                            <p>@plan.Day1</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 2:</strong>
                            <p>@plan.Day2</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 3:</strong>
                            <p>@plan.Day3</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 4:</strong>
                            <p>@plan.Day4</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 5:</strong>
                            <p>@plan.Day5</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 6:</strong>
                            <p>@plan.Day6</p>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4">
                        <div class="detail-item">
                            <strong>Day 7:</strong>
                            <p>@plan.Day7</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Action Links -->
        <div class="card profile-container shadow-lg rounded-lg">
            <div class="card-body text-center">
                <a class="btn btn-warning" asp-action="SendPdf">Send Me Detils my Subsecription</a> |

            </div>
        </div>
    }
    else
    {
        <div class="alert alert-warning" role="alert">
            You do not have any subscription
        </div>
    }
</div>


   
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

Fitness/Views/profileuser/MyVisaCard.cshtml
@model Fitness.Models.Payment

@{

    ViewData["Title"] = "Details";
    var UserRoleID = Context.Session.GetInt32("UserRoleID"); 

    if (UserRoleID.HasValue && (UserRoleID == 1))
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (UserRoleID.HasValue && (UserRoleID == 2))
    {
        Layout = "~/Views/Shared/_LayoutTrainer.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutProfilePage.cshtml";
    }
   

   
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="~/DesignProfileUser/style.css" id="bootstrap-css">
<link rel="stylesheet" href="~/DesignProfileUser/ditelsProfile.css" />
<link rel="stylesheet" href="~/css/UserVisaPage.css" />
<title>Confirmation</title>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        var message = '@TempData["SuccessMessage"]';
        if (message) {
            alert(message);
        }
    });
</script>

<div class="container mt-5">
@if (Model?.Amount != null)
{
    <div class="container mt-5">
        <!-- Card for Payment Details -->
        <div class="card profile-container shadow-lg rounded-lg mb-4">
            <div class="card-header">
                <h1>My Visa Card</h1>
            </div>
            <div class="card-body">
                <h4>Payment Details</h4>
                <hr />
                <dl class="row">
                    <div class="col-sm-6">
                        <dt>@Html.DisplayNameFor(model => model.Amount)</dt>
                        <dd>@Html.DisplayFor(model => model.Amount)</dd>
                    </div>
                    <div class="col-sm-6">
                        <dt>@Html.DisplayNameFor(model => model.Paymentdate)</dt>
                        <dd>@Html.DisplayFor(model => model.Paymentdate)</dd>
                    </div>
                    <div class="col-sm-6">
                        <dt>@Html.DisplayNameFor(model => model.Cardnumber)</dt>
                        <dd>@Html.DisplayFor(model => model.Cardnumber)</dd>
                    </div>
                    <div class="col-sm-6">
                        <dt>@Html.DisplayNameFor(model => model.Cardholdername)</dt>
                        <dd>@Html.DisplayFor(model => model.Cardholdername)</dd>
                    </div>
                    <div class="col-sm-6">
                        <dt>@Html.DisplayNameFor(model => model.Expirydate)</dt>
                        <dd>@Html.DisplayFor(model => model.Expirydate)</dd>
                    </div>
                </dl>
            </div>
            <div class="card-footer">
                <p>Visa Card Payment</p>
            </div>
        </div>
    </div>
    }
    else
    {
        <div class="alert alert-warning" role="alert">
            You don't have any visa card.
        </div>
    }

</div>